POST http://localhost:8080/expenses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJmaW5hbmNlcyIsInN1YiI6IjIiLCJleHAiOjE3MjU1MjI5MzIsImlhdCI6MTcyMTkyMjkzMn0.NwgOXKTIlpIIhmFUNtjBzGp_s9GeXWE5MLO21RBDJdZc7ivP5Y8rrBOVe1El5Kpxx7zO_XWqdFHFGLmR9pAHx7fpkv5NDYgf1o-YqSH0vg_ZK408sNLQqGgRg7Y48pEUYFEOjYUu_Jb59QdIWjaSsjMUaF9IH-iu-Pc9EhhuC38d6ieqoTJYIvkzHX3Q_XiPz_PkZPq5GEhgGTq2FuFKUHLvY19ULp1nWoMmthcvMW_Laqlzqj6PFx3Ack2lDdwpNyatG3z3gz_egGxubuiVRNj87yXud8SEfvfwe8cOPOhGaX_S85M9OtTpxSsNjAH7lXINDueHbTCoO35jISGINA

{
  "value": 100,
  "expenseCategoryId": 1,
  "userId": 2,
  "bankId": 1,
  "date": "2024-07-25T18:35:24.00Z",
  "description": "Bread and milk"
}

###
GET http://localhost:8080/expenses/1
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJmaW5hbmNlcyIsInN1YiI6IjIiLCJleHAiOjE3MjU1MjI5MzIsImlhdCI6MTcyMTkyMjkzMn0.NwgOXKTIlpIIhmFUNtjBzGp_s9GeXWE5MLO21RBDJdZc7ivP5Y8rrBOVe1El5Kpxx7zO_XWqdFHFGLmR9pAHx7fpkv5NDYgf1o-YqSH0vg_ZK408sNLQqGgRg7Y48pEUYFEOjYUu_Jb59QdIWjaSsjMUaF9IH-iu-Pc9EhhuC38d6ieqoTJYIvkzHX3Q_XiPz_PkZPq5GEhgGTq2FuFKUHLvY19ULp1nWoMmthcvMW_Laqlzqj6PFx3Ack2lDdwpNyatG3z3gz_egGxubuiVRNj87yXud8SEfvfwe8cOPOhGaX_S85M9OtTpxSsNjAH7lXINDueHbTCoO35jISGINA

###
GET http://localhost:8080/expenses/list/2
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJmaW5hbmNlcyIsInN1YiI6IjIiLCJleHAiOjE3MjU1MjI5MzIsImlhdCI6MTcyMTkyMjkzMn0.NwgOXKTIlpIIhmFUNtjBzGp_s9GeXWE5MLO21RBDJdZc7ivP5Y8rrBOVe1El5Kpxx7zO_XWqdFHFGLmR9pAHx7fpkv5NDYgf1o-YqSH0vg_ZK408sNLQqGgRg7Y48pEUYFEOjYUu_Jb59QdIWjaSsjMUaF9IH-iu-Pc9EhhuC38d6ieqoTJYIvkzHX3Q_XiPz_PkZPq5GEhgGTq2FuFKUHLvY19ULp1nWoMmthcvMW_Laqlzqj6PFx3Ack2lDdwpNyatG3z3gz_egGxubuiVRNj87yXud8SEfvfwe8cOPOhGaX_S85M9OtTpxSsNjAH7lXINDueHbTCoO35jISGINA

###
PUT http://localhost:8080/expenses/1
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJmaW5hbmNlcyIsInN1YiI6IjIiLCJleHAiOjE3MjU1MjI5MzIsImlhdCI6MTcyMTkyMjkzMn0.NwgOXKTIlpIIhmFUNtjBzGp_s9GeXWE5MLO21RBDJdZc7ivP5Y8rrBOVe1El5Kpxx7zO_XWqdFHFGLmR9pAHx7fpkv5NDYgf1o-YqSH0vg_ZK408sNLQqGgRg7Y48pEUYFEOjYUu_Jb59QdIWjaSsjMUaF9IH-iu-Pc9EhhuC38d6ieqoTJYIvkzHX3Q_XiPz_PkZPq5GEhgGTq2FuFKUHLvY19ULp1nWoMmthcvMW_Laqlzqj6PFx3Ack2lDdwpNyatG3z3gz_egGxubuiVRNj87yXud8SEfvfwe8cOPOhGaX_S85M9OtTpxSsNjAH7lXINDueHbTCoO35jISGINA
Content-Type: application/json

{
  "value": 101,
  "expenseCategoryId": 1,
  "userId": 2,
  "bankId": 1,
  "date": "2024-07-25T18:35:24.00Z",
  "description": "Bread and milk"
}

###
DELETE http://localhost:8080/expenses/1
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJmaW5hbmNlcyIsInN1YiI6IjIiLCJleHAiOjE3MjU1MjI5MzIsImlhdCI6MTcyMTkyMjkzMn0.NwgOXKTIlpIIhmFUNtjBzGp_s9GeXWE5MLO21RBDJdZc7ivP5Y8rrBOVe1El5Kpxx7zO_XWqdFHFGLmR9pAHx7fpkv5NDYgf1o-YqSH0vg_ZK408sNLQqGgRg7Y48pEUYFEOjYUu_Jb59QdIWjaSsjMUaF9IH-iu-Pc9EhhuC38d6ieqoTJYIvkzHX3Q_XiPz_PkZPq5GEhgGTq2FuFKUHLvY19ULp1nWoMmthcvMW_Laqlzqj6PFx3Ack2lDdwpNyatG3z3gz_egGxubuiVRNj87yXud8SEfvfwe8cOPOhGaX_S85M9OtTpxSsNjAH7lXINDueHbTCoO35jISGINA
